###################
# Global Settings #
###################

stages:
  - Env
  - Build_n_Test
  - Deploy

include:
  - .gitlab-ci/index.yaml

######################
# Build_n_Test Stage #
######################

.build_n_test:
  extends:
    - .job
  stage: Build_n_Test
  script:
    - module purge
    - module use ${CI_PROJECT_DIR}/spack_env
    - module load loads # module load compiler, deps, etc.
    - |
      if [[ ${CI_JOB_NAME} =~ "clang" ]];
      then
        module load clang/${FLECSALE_CLANG_VERSION};
      elif [[ ${CI_JOB_NAME} =~ "intel" ]];
      then
        module load intel/${FLECSALE_INTEL_VERSION};
      fi
    - module list
    - echo $CC
    - echo $CXX
    - mpiexec --version
    - nproc
    - echo 'Start building'
    - mkdir -p ${CI_PROJECT_DIR}/build
    - mkdir -p ${CI_PROJECT_DIR}/build/install
    - | # only need this block when we want to build and test against the latest libristra or flecsi-sp
      if [[ ${UPSTREAM_REPO} ]];
      then
        echo ${UPSTREAM_URL};
        echo ${UPSTREAM_REPO};
        echo ${UPSTREAM_BRANCH};
        cd ${CI_PROJECT_DIR}/${UPSTREAM_REPO};
        git fetch;
        git checkout ${UPSTREAM_BRANCH};
        git pull;
      fi
    - cd ${CI_PROJECT_DIR}/build/
    - echo ${FLECSALE_BUILD_TYPE}
    - echo ${FLECSALE_RUNTIME}
    #- ccache -z
    - |
      cmake -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/build/install \
            -DCMAKE_BUILD_TYPE=$FLECSALE_BUILD_TYPE \
            -DFLECSI_RUNTIME_MODEL=$FLECSALE_RUNTIME \
            -DENABLE_UNIT_TESTS=ON \
            -DENABLE_FLECSIT=OFF \
            -DENABLE_FLECSI_TUTORIAL=OFF \
            ..
    - make -k -j2 -l40 || make VERBOSE=1
    - make install DESTDIR=${CI_PROJECT_DIR}/build/install
    #- make install
    #- ccache -s
    - echo 'Start testing'
    - cd ${CI_PROJECT_DIR}/build/
    - make CTEST_OUTPUT_ON_FAILURE=1 test
    #- gcovr .

#######################################################################################
#######################################################################################
#######################################################################################
